### ISSUE TITLE
Multiple cross-compilers

### ISSUE THREAD

**Issue by staticmem** [abhiTronix/raspberry-pi-cross-compilers#108]
Is it possible to have more than one abhiTronix Raspberry Pi cross compiler tool chains installed so that the Include, LIBs, etc. paths don't conflict?

Am I correct in assuming that the Raspberry Pi Model 1 (32 bit) cross compiler code  can be executed on any model as long as those models have the required 32 bit libs installed too.  That works for me at present but I may want to use 64 bit coded binaries at some stage.

Also if I build a 32 bit binary and it's built with the -static option do I still need 32 bit libs?

**Comment by abhiTronix** [comment]
> Is it possible to have more than one abhiTronix Raspberry Pi cross compiler tool chains installed so that the Include, LIBs, etc. paths don't conflict?

Yes, All cross-compiler are path specific. So as long as paths are handle properly, there will no conflict. 


> Am I correct in assuming that the Raspberry Pi Model 1 (32 bit) cross compiler code can be executed on any model as long as those models have the required 32 bit libs installed too

No,  Raspberry Pi Model 1 (32 bit) cross compiler code will work only on **Raspberry Pi - Zero/W/WH & 1 Model A/B/A+/B+** models not on any others. On top of that, Raspberry Pi Model 1 (32 bit) cross compiler code built using **_Raspberry Pi GCC Cross-Compiler Toolchains (Bullseye)_** only works on Bullseye 32-bit OS (Debian Version 11) and not on other Debian versions such as Stretch or Buster. 

> That works for me at present but I may want to use 64 bit coded binaries at some stage.

64-bit binaries are completely different than 32-bit binaries. 64-bit(ARM64/AArch64) Raspberry Pi GCC Toolchains only support [Raspberry Pi Models/Versions with ARMv8-a CPU Architecture](https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki/Supported-Raspberry-Pi-Models-with-ARMV8A-Architecture#the-supported-raspberry-pi-models-with-arm8-a-architecture-are-as-follows) AND Raspberry Pi 64-Bit OS flavors with 64-bit kernel only (such as [Raspbian Buster 64-bit OS](https://downloads.raspberrypi.org/raspios_arm64/images/)).
