### ISSUE TITLE
crt1.o: No such file or directory.

### ISSUE THREAD

**Issue by larsk2009** [abhiTronix/raspberry-pi-cross-compilers#112]
Hi,

Thanks for this project. I am getting this error: `cannot find crt1.o: No such file or directory` and `cannot find crti.o: No such file or directory` while cmake tries to compile the "simple test program". I looked trough some existing issue but I couldn't fix it. I see that my sysroot does contain these files so I am unsure what the issue is. Do you have any ideas?

**Comment by gsieben** [comment]
You must follow the instructions carefully. Also the steps on the Raspberry are important. 

You probably have step 

Steps/Settings for Target Machine (Raspberry Pi): 8. Setup Important Symlinks as follows: (Important)

of the instructions. 

This must be executed on the Raspberry before the files are dragged to the host with rsync.

Steps/Settings for Host Machine (PC/Laptop): 4. sync Raspberry Pi rootfs (Most Important)

**Comment by abhiTronix** [comment]
@larsk2009 This is a configuration issue and not toolchain issue, kindly read docs properly and resolve this at your end.
