### ISSUE TITLE
(enhancement) Bump to gcc 8.3.0

### ISSUE THREAD

**Issue by krcroft** [abhiTronix/raspberry-pi-cross-compilers#12]
Thank you for the build!

**Comment by jimcruse** [comment]
Any update on release

**Comment by jimcruse** [comment]
I see sourceforge files were updated to 8.3;  github readme.md, still shows 8.2; so thank you very much, I'll give them a shot, thanks

**Comment by abhiTronix** [comment]
Closed in 2f87bc2899512822073d8228168c0f7da62154e2

**Comment by krcroft** [comment]
Thank you!
