### ISSUE TITLE
Install scripts 

### ISSUE THREAD

**Issue by jimcruse** [abhiTronix/raspberry-pi-cross-compilers#15]
Is it safe to modify them for 8.3, you said don't modify because of security....

**Comment by abhiTronix** [comment]
@jimcruse scripts are currently not supported as depicted in [Readme Section](https://github.com/abhiTronix/raspberry-pi-cross-compilers/blob/master/Tools/README.md). **Kindly strictly follow the instruction. Proceed at your own risk!
