### ISSUE TITLE
Your readme.md links to the GitHub wiki, which is empty

### ISSUE THREAD

**Issue by jimcruse** [abhiTronix/raspberry-pi-cross-compilers#18]
Inside the readme.md where it says to be sure to read carefully for native instructions

**Comment by jimcruse** [comment]
https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki/Native-Compiler:-Linking-&-Testing-Instructions

**Comment by abhiTronix** [comment]
> Your readme.md links to the GitHub wiki, which is empty
> Inside the readme.md where it says to be sure to read carefully for native instructions
> https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki/Native-Compiler:-Linking-&-Testing-Instructions
@jimcruse what do you mean by empty??? Links are all working fine.  **Share a screenshot.**

**Comment by abhiTronix** [comment]
@jimcruse I'm closing this due to lack of information, Kindly provide proper & detailed information to elaborate your issue. Goodluck.
