### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by zouchry** [abhiTronix/raspberry-pi-cross-compilers#2]
I used " https://media.githubusercontent.com/media/abhiTronix/raspberry-pi-cross-compilers/master/gcc-8.2.0.tar.bz2" command to download the target file, got the 404 error. can you help me to solve the problem? Thanks!

**Comment by abhiTronix** [comment]
@zouchry I'm moving files to Sourceforge soon.

**Comment by abhiTronix** [comment]
@zouchry 

> I used " https://media.githubusercontent.com/media/abhiTronix/raspberry-pi-cross-compilers/master/gcc-8.2.0.tar.bz2" command to download the target file, got the 404 error. can you help me to solve the problem? Thanks!

 The issue is resolved now, **Updated SourceForge Link in the ReadMe Section**. Good luck :+1:

**Comment by abhiTronix** [comment]
> I used " https://media.githubusercontent.com/media/abhiTronix/raspberry-pi-cross-compilers/master/gcc-8.2.0.tar.bz2" command to download the target file, got the 404 error. can you help me to solve the problem? Thanks!
