### ISSUE TITLE
Documentation seems to be missing part of setup in the script

### ISSUE THREAD

**Issue by jimcruse** [abhiTronix/raspberry-pi-cross-compilers#20]
I know I can't use experimental install script, but it seems, that the readme.md: 
The script has a section where links are set up /usr/bin links to /opt/ such as: 
But I can't find the equivalent section in the readme/nativeCompiler
such as:

sudo ln -s /opt/native-pi-gcc-8.3.0-2/bin/arm-linux-gnueabihf-g++-8.3.0 g++

**Comment by abhiTronix** [comment]
@jimcruse As you have been warned previously in [this comment](https://github.com/abhiTronix/raspberry-pi-cross-compilers/issues/19#issuecomment-475933021) that clearly stated not to open multiple issues of the same kind, thereby any new issue from your end will be marked invalid straightaway if this term is violated. **Kindly DO NOT open new issue that is related to any previous issue discussed on this repo., I repeat**
