### ISSUE TITLE
error: ‘armv8-a’ does not support feature ‘fp’

### ISSUE THREAD

**Issue by dschnabel** [abhiTronix/raspberry-pi-cross-compilers#25]
When I build with the 9.1.0 cross-compiler toolchain and use the flag `-march=armv8-a+fp+simd` as mentioned in the README, I'm getting this error message:

```
make all 
Building file: ../src/hello.cpp
Invoking: Cross G++ Compiler
arm-linux-gnueabihf-g++ -O0 -march=armv8-a+fp+simd -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/hello.d" -MT"src/hello.o" -o "src/hello.o" "../src/hello.cpp"
arm-linux-gnueabihf-g++: error: ‘armv8-a’ does not support feature ‘fp’
arm-linux-gnueabihf-g++: note: valid feature names are: crc simd crypto nocrypto nofp sb predres; did you mean ‘nofp’?
make: *** [src/hello.o] Error 1
```

Looks like `fp` is the default, so I can omit that and just use `-march=armv8-a+simd`? It builds fine without it.

**Comment by abhiTronix** [comment]
@dschnabel **Kindly make sure that flag `-march=armv8-a+fp+simd` is only available with [64-bit toolchains](https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki#bonus-64-bit-arm64-gcc-compilers-toolchains). If you are using [32-bit-toolchains](https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki/Cross-Compiler:-Installation-Instructions) kindly use  `-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8` combination instead. For more information see [here](https://github.com/abhiTronix/raspberry-pi-cross-compilers#optimization-flags-involved).**
