### ISSUE TITLE
[Enhancement]  Bump to gcc v9.2 and GDB v8.3.1

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/raspberry-pi-cross-compilers#28]
### Summary:

_New **GCC 9.2 and GDB 8.3.1** have just released. Latest Binaries builds is in Progress!_

**Comment by krcroft** [comment]
Thumbs up to that; looking forward to the new build!  Thank you @abhiTronix

**Comment by abhiTronix** [comment]
Thanks, I'll be updating remaining binaries shortly. Have a nice day!
