### ISSUE TITLE
Documentation says 9.1 even when 9.2 is also available

### ISSUE THREAD

**Issue by jimcruse** [abhiTronix/raspberry-pi-cross-compilers#31]
Documentation says latest gcc vs 9.1 even though 9.2 is available, on your sourceforge site... 
I know it actually has both 9.1 and 9.2 it just gets confusing
And I think you should get credit for being 9.2 , which I've been using for a month or so..

**Comment by abhiTronix** [comment]
@jimcruse Sure, doing it now.

**Comment by abhiTronix** [comment]
**Successfully resolved in commit 5663480**
