### ISSUE TITLE
Download address of gcc is error at script build-scripts/RTBuilder_32b

### ISSUE THREAD

**Issue by jackyxinli** [abhiTronix/raspberry-pi-cross-compilers#43]
line 169, download address of gcc is error, should be "https://ftpmirror.gnu.org/gnu/gcc/gcc-$GCCBASE_VERSION/gcc-$GCCBASE_VERSION.tar.gz"

**Comment by abhiTronix** [comment]
@jackyxinli No it automatically redirects to original mirror, for e.g. see https://ftpmirror.gnu.org/gcc/gcc-6.3.0/gcc-6.3.0.tar.gz

**Comment by abhiTronix** [comment]
[`wget` allows max redirects upto 20](http://www.gnu.org/software/wget/manual/html_node/HTTP-Options.html) which is far more than ideal. I don't think this redirecting affects anything in general. Closing.
