### ISSUE TITLE
How to add c standard header files and libraries into compress package file of native gcc?

### ISSUE THREAD

**Issue by jackyxinli** [abhiTronix/raspberry-pi-cross-compilers#45]
Hi, I modify file "build-scripts/RTBuilder_32b", change GLIBC_VERSION from 2.24 to 2.23, then I get cross-gcc and native-gcc after 2 hours. I copy file "native-gcc-9.3.0-pi_2-3.tar.gz" into my development board(cpu is imx6ull), uncompress into /usr/local, change environment PATH as "PATH=/usr/local/bin:$PATH", then create a file "hello.c" only call function "printf", but folder "/usr/local/include" does not contain header file "stdio.h".
How to add c standard header files and libraries into compress package file of native gcc?

**Comment by abhiTronix** [comment]
Just follow this wiki instructions: https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki/Native-Compiler:-Installation-Instructions#raspberry-pi-gcc-native-compiler-arm-toolchains-setup-guide . Also, Please refrain from opening multiple issues of same type.
