### ISSUE TITLE
Why does not copy compiled binaries of glibc into both cross-gcc and native-gcc?

### ISSUE THREAD

**Issue by jackyxinli** [abhiTronix/raspberry-pi-cross-compilers#46]
As my opinion, we can keep completion of both cross-gcc and native-gcc if script could copy compiled binaries of glibc into two edition.
Another question is need add option --disable-werror when configure glibc if version is lower than current system is, like version 2.23. I add this option to configure then I get the whole binaries of glibc-2.23.

regards,
jackyxinli

**Comment by abhiTronix** [comment]
@jackyxinli Your duplicate issue will be closed immediately without resolving. **Kindly comment under previous issue.**
