### ISSUE TITLE
binutils build as target edition is missed

### ISSUE THREAD

**Issue by jackyxinli** [abhiTronix/raspberry-pi-cross-compilers#48]
native gcc edition miss binutils which should be compiled as target edition, like as and ld. When run gcc -o hello hello.c, get error message that ld is missing

**Comment by abhiTronix** [comment]
> native gcc edition miss binutils

That makes no sense. You can yourself review build scripts. 

> When run gcc -o hello hello.c, get error message that ld is missing

It's `gcc-{downloaded GCC version}` not `gcc`.
