### ISSUE TITLE
Textinfo vs texinfo

### ISSUE THREAD

**Issue by jimcruse** [abhiTronix/raspberry-pi-cross-compilers#5]
Documentation show module texTinfo needed - no such module found by apt-get 
There is texTinfo

**Comment by jimcruse** [comment]
Textinfo vs texinfo

**Comment by abhiTronix** [comment]
Fixed in https://github.com/abhiTronix/raspberry-pi-cross-compilers/commit/17c9e29224594648f934a4b5c279413151bc0b44
