### ISSUE TITLE
I get errro after modify configuration

### ISSUE THREAD

**Issue by jackyxinli** [abhiTronix/raspberry-pi-cross-compilers#53]
Hi, abhiTronix
I have question about compile cross gcc at stage 1.

original configuration is:
../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot=$SYSROOTDIR --with-tune=$TUNE --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --with-mode=$MODE --disable-multilib
make -s -j$(nproc) all-gcc
make -s install-gcc DESTDIR=$INSTALLDIR
this script will work and generate gcc

when I modify like this:
../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/ --with-build-sysroot=$SYSROOTDIR --with-tune=$TUNE --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --with-mode=$MODE --disable-multilib
make -s -j$(nproc) all-gcc
make -s install-gcc DESTDIR=$INSTALLDIR
this script will fail and give me an error, why?

Hope your reply.

**Comment by abhiTronix** [comment]
What is at `--with-sysroot=/ `? and why it is related to this repository? Sorry but this is completely unrelated.
