### ISSUE TITLE
gcc debs .... feature request

### ISSUE THREAD

**Issue by xevilstar** [abhiTronix/raspberry-pi-cross-compilers#56]
does this build the .deb files?
if not could you add this feature as an option?

**Comment by abhiTronix** [comment]
> does this build the .deb files?

Not yet. The only problem is we compile every binary together as whole which is lot easier to setup and compatible with almost any Linux distribution. So it feels redundant to switch to deb packages instead of compressed binaries. But we would love to have this feature, any PR is welcomed.
