### ISSUE TITLE
cannot find crt1.o: No such file or directory

### ISSUE THREAD

**Issue by MhmRhm** [abhiTronix/raspberry-pi-cross-compilers#58]
Hello, I encounter this error **cannot find crt1.o: No such file or directory** when I'm using 8.3.0 or 10.2.0 toolchains.
This is my complete `/qt5.15.2/configure` out put:
[configure2020-12-04_21-32.log](https://github.com/abhiTronix/raspberry-pi-cross-compilers/files/5644582/configure2020-12-04_21-32.log)
and I'm using this command:
`../qt5.15.2/configure -opengl es2 -device linux-rasp-pi4-v3d-g++ -device-option CROSS_COMPILE=/home/mohammad/Programs/Raspberry/raspiToolchains/cross-pi-gcc-10.2.0-2/bin/arm-linux-gnueabihf- -sysroot /home/mohammad/Programs/Raspberry/qt5pi4B/sysroot -prefix /usr/local/qt5pi -extprefix /home/mohammad/Programs/Raspberry/qt5pi4B/targetBinaries -hostprefix /home/mohammad/Programs/Raspberry/qt5pi4B/hostBinaries -opensource -confirm-license -release -v -nomake examples -no-use-gold-linker -recheck-all 2>&1 | tee ../configure$(date +"%Y-%m-%d_%H-%M").log`

when I change the croos compiler to something else for example this command:
`../qt5.15.2/configure -opengl es2 -device linux-rasp-pi4-v3d-g++ -device-option CROSS_COMPILE=/home/mohammad/Programs/Raspberry/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf- -sysroot /home/mohammad/Programs/Raspberry/qt5pi4B/sysroot -prefix /usr/local/qt5pi -extprefix /home/mohammad/Programs/Raspberry/qt5pi4B/targetBinaries -hostprefix /home/mohammad/Programs/Raspberry/qt5pi4B/hostBinaries -opensource -confirm-license -release -v -nomake examples -no-use-gold-linker -recheck-all 2>&1 | tee ../configure$(date +"%Y-%m-%d_%H-%M").log`
everything is fine.

and finally this is my directories:
```
├── qt5pi4B
│   ├── build
│   ├── configure2020-12-04_21-32.log
│   ├── qt5.15.2
│   ├── sysroot
│   └── sysroot-relativelinks.py
└── raspiToolchains
    ├── cross-pi-gcc-10.2.0-2
    ├── cross-pi-gcc-8.3.0-2
    └── gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf
```

**Comment by abhiTronix** [comment]
> Hello, I encounter this error cannot find crt1.o: No such file or directory when I'm using 8.3.0 or 10.2.0 toolchains.
This is my complete /qt5.15.2/configure out put:
configure2020-12-04_21-32.log
and I'm using this command:
../qt5.15.2/configure -opengl es2 -device linux-rasp-pi4-v3d-g++ -device-option CROSS_COMPILE=/home/mohammad/Programs/Raspberry/raspiToolchains/cross-pi-gcc-10.2.0-2/bin/arm-linux-gnueabihf- -sysroot /home/mohammad/Programs/Raspberry/qt5pi4B/sysroot -prefix /usr/local/qt5pi -extprefix /home/mohammad/Programs/Raspberry/qt5pi4B/targetBinaries -hostprefix /home/mohammad/Programs/Raspberry/qt5pi4B/hostBinaries -opensource -confirm-license -release -v -nomake examples -no-use-gold-linker -recheck-all 2>&1 | tee ../configure$(date +"%Y-%m-%d_%H-%M").log

**Are you ignorant or something? When there's a [dedicated guide available](https://github.com/abhiTronix/raspberry-pi-cross-compilers/blob/master/QT_build_instructions.md) in wikis, why you still using the same old wrong commands?** Also, When there's a pinned issue namely [**QT build instructions for Raspberry Pi**](https://github.com/abhiTronix/raspberry-pi-cross-compilers/issues/55), and a similar issue #27 available, then why cannot you just open those first, before blindly opening this same issue again 🤦‍♂️. This just ridiculous.
