### ISSUE TITLE
Exec format error when trying execute gcc-8.2.0

### ISSUE THREAD

**Issue by jimcruse** [abhiTronix/raspberry-pi-cross-compilers#7]
After all the setup I now get an exec format error
I now get an: root@raspberrypi:/home/pi/gcc_all/cross-pi-gcc-8.2.0/bin# .arm-linux-gnueabihf- gcc-8.2.0 bash: ./arm-linux-gnueabihf-gcc-8.2.0: cannot execute binary file: Exec format error

**Comment by jimcruse** [comment]
I reinstalled everything from scratch and got it working, had to relink g++ to /opt/gcc-8.2.0/bin/arm-linux-gnueabihf-g++

**Comment by abhiTronix** [comment]
> I reinstalled everything from scratch and got it working, had to relink g++ to /opt/gcc-8.2.0/bin/arm-linux-gnueabihf-g++

@jimcruse This Bug is fixed in commit https://github.com/abhiTronix/raspberry-pi-cross-compilers/commit/645352297e1074e5a0ab27c354ace6a1914b8467 . **Kindly Try ReadMe section again. Thankyou**

**Comment by jimcruse** [comment]
I'll try next week, I broke my raspberry pi
