### ISSUE TITLE
Add more flags for the Raspberry Pi 4

### ISSUE THREAD

**Issue by heavygabriel** [abhiTronix/raspberry-pi-cross-compilers#73]
Hi! 
I'm a optimizer maniac and I see that there are not a lot of C/CXX FLAGS that the toolchain is compiled with.
Anyways, I use
` -march=armv8-a+simd+crc+fp+nocrypto -mcpu=cortex-a72+simd+crc+fp+nocrypto -mtune=cortex-a72 -ftree-vectorize -fomit-frame-pointer --param l1-cache-size=80` for my C/CXX flags and I think that this project could benefit from them.

**Comment by abhiTronix** [comment]
@heavygabriel These flags are 64bit specific and I don't think so it would be ideal  to hardcode machine specific flags as these toolchains are used for many ARM devices beside raspberry pi.
